SET SERVEROUTPUT ON;
DECLARE 
RNO NUMBER;
M1 NUMBER;
NAME VARCHAR(20);
GRADE VARCHAR(20);
CURSOR C1 IS SELECT ROLL,NAME,MARKS FROM STUDENT;
BEGIN
OPEN C1;
LOOP
FETCH C1 INTO RNO,NAME,M1;
EXIT WHEN C1%NOTFOUND;
SELECT MYFUN(RNO) INTO GRADE FROM DUAL;
INSERT INTO RESULT_1 VALUES(RNO,NAME,GRADE);
END LOOP;
END;