SET SERVEROUTPUT ON;
DECLARE
	CURSOR PARAM_CURSOR (ROLL NUMBER) IS SELECT ROLL_NO,NAME,MARKS FROM STUD_MARKS
	WHERE ROLL_NO = ROLL;
	TMP PARAM_CURSOR%ROWTYPE;
    A NUMBER;
BEGIN
     A:=&no;
     
	FOR TMP IN PARAM_CURSOR (A) 
    LOOP
	dbms_output.put_line('NAME    '||TMP.NAME);
	dbms_output.put_line('Marks:  '||TMP.MARKS);
	END Loop;
END;	
