SET SERVEROUTPUT ON;
DECLARE
RNO NUMBER;
DOI DATE;
NOB VARCHAR(20);
NOD NUMBER;
AMT NUMBER;


BEGIN
RNO:= &RNO;
NOB:='&NOB';
SELECT DATEOFISSUE INTO DOI FROM BORROWER1 WHERE ROLLNO=RNO AND NAMEOFBOOK=NOB;
NOD:=SYSDATE-DOI;
IF(NOD>15 AND NOD<30)THEN
AMT:=NOD*5;
ELSIF(NOD>30)THEN
AMT:=NOD*50;
ELSE
DBMS_OUTPUT.PUT_LINE('NO FINE');
END IF;
IF(NOD>15)THEN
INSERT INTO FINE1 VALUES(RNO,SYSDATE,AMT);
END IF;
UPDATE BORROWER1 SET STATUS='R' WHERE ROLLNO=RNO AND NAMEOFBOOK=NOB;
EXCEPTION 
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO RECORD');
END;